clear all;
close all;
clc;
data=load('control2.mat');
x=data.data(:,1);
y=data.data(:,2)*3/255;
xs=166;
xf=5140;
ymax=0.45;
ymin=0.1;
ts=xs/10;
tf=xf/10;
ci=mean(y(1:xs));
cf=mean(y(xf:length(y)));
stdi=std(y(1:xs));
stdf=std(y(xf:length(y)));

t=x/10;
plot(t,y,'k'); grid on;
axis([0 522 0 0.5]);
% axis([0 522 0 50]);
xlabel ('Tiempo (s)');
ylabel ('Contraste');
title('Evolución del contraste en el tiempo','FontWeight', 'bold','FontSize',14);
line([ts ts tf tf ts],[ymin ymax ymax ymin ymin],'Color','r','LineWidth',2);
txt1=text(25,0.06,['Contraste Inicial: ', num2str(ci,'%.4f'), ' \pm ',num2str(stdi,'%.4f')], 'BackgroundColor',[1 1 1]);
txt2=text(25,0.025,['Contraste Final:   ', num2str(cf,'%.4f'), ' \pm ',num2str(stdf,'%.4f')], 'BackgroundColor',[1 1 1]);
txt3=text((tf-ts)/2,ymin,'Proceso de ajuste','HorizontalAlignment','center', 'BackgroundColor','r','FontWeight','bold','color','w');
